"""Artifacts and logs page."""

from __future__ import annotations

import streamlit as st

from ui.pages.common import preview_artifact, render_markdown_block, render_page_intro, render_table


def render(state: dict, ui_state: dict) -> None:
    render_page_intro(
        "Artifacts / Logs",
        "This page exposes the synced reproducibility indexes, manifest inventory, and log inventory in a read-only way. Panel-friendly mode stays high-level; advanced mode allows direct artifact preview and download.",
        badge="Read-only artifact browser",
    )

    catalog = state["final_output_catalog"]
    manifests = state["final_manifest_index"]
    logs = state["final_log_index"]

    tabs = st.tabs(["Output catalog", "Manifest index", "Log index", "Package notes"])

    with tabs[0]:
        render_table(
            "Final output catalog",
            catalog,
            download_name="final_output_catalog.csv",
            caption="This catalog is regenerated by the Phase 5 sync and is the safest way to see what artifact groups exist right now.",
            height=320,
            max_rows=None if ui_state["advanced"] else 40,
        )
        if ui_state["advanced"] and not catalog.empty:
            selected = st.selectbox("Preview output artifact", catalog["relative_path"].astype(str).tolist(), key="catalog_preview")
            preview_artifact(selected)

    with tabs[1]:
        render_table(
            "Final manifest index",
            manifests,
            download_name="final_manifest_index.csv",
            caption="Manifest inventory pulled from the synced final reproducibility package.",
            height=320,
            max_rows=None if ui_state["advanced"] else 40,
        )
        if ui_state["advanced"] and not manifests.empty:
            selected = st.selectbox("Preview manifest", manifests["relative_path"].astype(str).tolist(), key="manifest_preview")
            preview_artifact(selected)

    with tabs[2]:
        render_table(
            "Final log index",
            logs,
            download_name="final_log_index.csv",
            caption="Log preview stays read-only. Missing optional logs are tolerated.",
            height=260,
            max_rows=None if ui_state["advanced"] else 30,
        )
        if ui_state["advanced"] and not logs.empty:
            selected = st.selectbox("Preview log", logs["relative_path"].astype(str).tolist(), key="log_preview")
            preview_artifact(selected)

    with tabs[3]:
        render_markdown_block("Publication captions", state["publication_captions"], collapsed=True)
        render_markdown_block("Publication talking points", state["publication_talking_points"], collapsed=True)
